name: comp_workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scipy
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - tqdm
  - h5py
  - pytables
  - seaborn
  - ipywidgets
  - jupyter
  - jupyterlab
  - pip
