##### Task #####
task: CompWorkflow

##### Model parameters #####
model:
  batch_size: 24576
  lr: 0.001

##### Training parameters #####
train:
  num_epochs: 5
  num_workers: 6
  save_summary_steps: 5
  checkpoint: ''

##### Regularization parameters #####
regularization:
  weight_decay: 0.0001

